name: Docker

on: [push, pull_request]

env:
  IMAGE_NAME: toolchain

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - gcc: 4.8.0

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install help2man libtool-bin libncurses5-dev
      - name: Download release
        run: wget "https://ftp.gnu.org/gnu/gcc/gcc-${{matrix.gcc}}/gcc-${{matrix.gcc}}.tar.bz2"
      - run: |
          echo 'CT_CONFIG_VERSION="3"' > defconfig
          echo 'CT_ARCH_ARM=y' >> defconfig
          echo 'CT_TARGET_VENDOR="none"' >> defconfig
          echo 'CT_LOG_PROGRESS_BAR=n' >> defconfig
          echo 'CT_CC_GCC_EXTRA_CONFIG_ARRAY="--with-gnu-ld --with-gnu-as"' >> defconfig
          echo 'CT_EXPERIMENTAL=y' >> defconfig
          echo 'CT_GCC_SRC_CUSTOM=y' >> defconfig
          echo 'CT_GCC_CUSTOM_LOCATION="gcc-${{matrix.gcc}}.tar.bz2"' >> defconfig
      - name: Build the toolchain
        run: ${{github.workspace}}/imagefiles/install-crosstool-ng-toolchain.sh -p ${{runner.workspace}}/out -c defconfig
