name: Docker

on: [push, pull_request]

env:
  IMAGE_NAME: toolchain

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install help2man
      - name: Build the toolchain
        run: ${{github.workspace}}/imagefiles/install-crosstool-ng-toolchain.sh -p ${{runner.workspace}}/out -c defconfig
