name: Docker

on: [push, pull_request]

env:
  IMAGE_NAME: toolchain

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - gcc: 4.8.0
            var: CT_GCC_V_4_8

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install help2man libtool-bin libncurses5-dev
      - name: Download release
        run: wget "https://ftp.gnu.org/gnu/gcc/gcc-${{matrix.gcc}}/gcc-${{matrix.gcc}}.tar.bz2"
      - run: tar xjf "gcc-${{matrix.gcc}}.tar.bz2" -C ${{runner.workspace}}
      - run: pwd
      - run: ls ${{runner.workspace}}
      - run: ls ${{runner.workspace}}/gcc-${{matrix.gcc}}
      - run: |
          echo 'CT_CONFIG_VERSION="3"' > defconfig
          echo 'CT_ARCH_ARM=y' >> defconfig
          echo 'CT_TARGET_VENDOR="none"' >> defconfig
          echo 'CT_LOG_PROGRESS_BAR=n' >> defconfig
          echo 'CT_CC_GCC_EXTRA_CONFIG_ARRAY="--with-gnu-ld --with-gnu-as"' >> defconfig
          echo 'CT_OBSOLETE=y' >> defconfig
          echo 'CT_EXPERIMENTAL=y' >> defconfig
          echo 'CT_GCC_SRC_CUSTOM=y' >> defconfig
          echo 'CT_GCC_CUSTOM_LOCATION="${{runner.workspace}}/gcc-${{matrix.gcc}}"' >> defconfig
          echo '${{matrix.var}}=y' >> defconfig
      - name: Build the toolchain
        run: ${{github.workspace}}/imagefiles/install-crosstool-ng-toolchain.sh -p ${{runner.workspace}}/out -c defconfig
