name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches: [ master ]

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: toolchain

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the toolchain
        run: ./install-crosstool-ng-toolchain.sh
